[package]
name = "make_passwords"
version = "0.1.0"
authors = ["Tomo <eyixw.3mke3xd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
clap = "3.0.0-beta.2"
rand = "0.8.3"
